name: Dummy Composite Action
description: A dummy composite action that prints hello world.

runs:
  using: composite
  steps:
    - name: Print hello from composite action
      shell: bash
      run: echo "hello world from action!"

    - name: Action reference via semver tag (intentionally old for dependabot updates)
      if: ${{ false }}
      # expected_behavior: replace tag by commit sha that the tag points to
      # The v3 tag is already the latest 3.x version since the latest tag v3.9.1 points to the same commit like v3
      # Commit for v3: 3235b876344d2a9aa001b8d1453c930bba69e610
      uses: actions/setup-node@v3
    - name: Action reference via commit with version comment
      if: ${{ false }}
      # expected_behavior: newest_semver_compatible_tag_commit
      # 0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0 & v3
      # 1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    - name: Action reference via commit with version comment
      if: ${{ false }}
      # expected_behavior: newest_semver_compatible_tag_commit
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # 4.2.0
    - name: Action reference via commit with major version comment
      if: ${{ false }}
      # expected_behavior: newest_semver_compatible_tag_commit
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
    - name: Action reference via commit with wrong version comment
      if: ${{ false }}
      # v4.7.12 does not exist at all
      # expected_behavior: newest_semver_compatible_tag_commit for 4.x
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.7.12

    - name: Action reference via commit without version comment
      if: ${{ false }}
      # expected_behavior: Resolve commit to semver tag and then update to newest semver compatible tag
      # Expected commit sha is 34e114876b0b11c390a56381ad16ebd13914f8d5 which is version v4.3.1
      # Commit that belongs to version 4.1.0
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Action reference via commit without version comment and without any tags in the repo
      if: ${{ false }}
      # expected/wished behavior: Replace current commit by latest commit on default branch
      # result: No update at all since there is no comment saying from where to update
      uses: mtombosch/cicd-actions/inter-repo-access@51883d9cd772bee5b7d139a2e6ffd8aeabca4224

    - name: Action reference via commit with multi path version comment
      if: ${{ false }}
      # expected_behavior: update tag to dummy-composite/v1.0.1 or next minor version if it exists
      # Repo has multiple tags (for the dummy action and dummy workflow)
      uses: mtombosch/dependabot_update_scenarios_test/.github/actions/dummy-composite@150be11f8e18450c38116b01268b2b7119b87931 # dummy-composite/v1.0.0

    - name: Action reference via commit with multi path version comment 2
      if: ${{ false }}
      # expected_behavior: update tag to dummy-composite/v1.0.1 or next minor version if it exists
      # Repo has multiple tags (for the dummy action and dummy workflow)
      uses: mtombosch/dependabot_update_scenarios_test/.github/actions/dummy-composite@dummy-composite/v1.0.0
